# Site settings
author: NaKia Whitby
title: DecodeHer
header-img: img/home-bg.png
email: whitby.nakia@gmail.com
copyright_name: NaKia Whitby
description: > # this means to ignore newlines until "baseurl:"
  The Reversed Engineered "Me" (Version 2.0)
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  NWhitby

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
